language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "13"

before_install:
  - "export CHROME_BIN=chromium-browser"
  - "export BROWSERS=Firefox"
services:
  - xvfb
after_success:
  - yarn cover-publish
addons:
  code_climate:
    repo_token:
      # # get your token from https://codeclimate.com/github/benjamine/jsondiffpatch
      # gem install travis
      # travis encrypt <projecttoken>
      secure: "IZabDj3HrrCNOfhK0v+Q/am9AE5zYzF13IYB64q8wSUHcSxxhdrxSyLvjIiOfLe9W+h+MAW1+OuQkldUs/yd/fJjy44GE4ugUKY+9RP3TBm7hQRF4KEwIx2BMK4HVNazOkWz8nsnq4cfPy9pFEumcKb/O7TL2gK6RS6dIfNsKw0="
